---
# tasks file for ansible-role-ipafont

## ipafontのzipを解凍
- name: Unarchive a file that needs to be downloaded
  unarchive:
    src: "{{ ipafont_zip_url }}"
    dest: "{{ fonts_resource_dir }}"
    remote_src: yes
    list_files: yes
